/*
 * MIT License
 *
 * Copyright (c) 2016-2023 Objectionary.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
import com.jcabi.xml.XMLDocument

// Check logs first.
String log = new File(basedir, 'build.log').text;
assert log.contains("BUILD SUCCESS")
// Check success.
// @todo #219:90min Compare XML files generated by the plugin with the expected ones.
//  We use .replace(' ', '') to ignore spaces in the comparison.
//  This is a temporary solution, we need to find a better way to compare XML files.
//  You can check some answers here: https://stackoverflow.com/questions/141993/best-way-to-compare-2-xml-documents-in-java
//  https://stackoverflow.com/q/13727876/10423604
XMLDocument expected = new XMLDocument(new File(basedir, 'target/generated-sources/jeo-xmir/org/eolang/jeo/Bar.xmir'));
XMLDocument decompile = new XMLDocument(new File(basedir, 'target/generated-sources/opeo-decompile-xmir/org/eolang/jeo/Bar.xmir'));
XMLDocument compile = new XMLDocument(new File(basedir, 'target/generated-sources/opeo-compile-xmir/org/eolang/jeo/Bar.xmir'));
// We expect the same output.
assert compile.toString().replace(' ', '') == expected.toString().replace(' ', '')
assert decompile.toString().replace(' ', '') == expected.toString().replace(' ', '')
true